version: '3'
services:
  om2m-in-cse:
    build: 
      context: ./OM2M
    working_dir: /home/in-cse
    entrypoint: sh start.sh
    stdin_open: true
    tty: true
    ports:
      - "10001:8080"
      #- "5683:5683"
    volumes:
      - "./OM2M/configuration/config.ini:/home/in-cse/configuration/config.ini"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
    depends_on:
      - mqtt-broker
      - nginx-proxy
    links:
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto:latest
    command: /bin/sh -c "touch /mosquitto/config/pwfile && /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./MQTT/config:/mosquitto/config"
      - "./MQTT/data:/mosquitto/data"
      - "./MQTT/log:/mosquitto/log"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "10002:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx/default_location.conf:/etc/nginx/vhost.d/default_location"