version: '3'
services:
  om2m-in-cse:
    build: 
      context: ./OM2M
    working_dir: /home/in-cse
    entrypoint: sh start.sh
    stdin_open: true
    tty: true
    ports:
     - "8080:8080"
    volumes:
     - ./OM2M/config.ini:/home/in-ces/configuration

  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
     - "1883:1883"
     - "9001:9001"
    volumes:
     - ./MQTT/mosquitto.conf:/mosquitto/config/mosquitto.conf
     - ./MQTT/data:/mosquitto/data
     - ./MQTT/log:/mosquitto/log
