version: '3'
services:
  om2m-in-cse:
    build: 
      context: ./OM2M
    working_dir: /home/in-cse
    entrypoint: sh start.sh
    stdin_open: true
    tty: true
    ports:
      - "10001:8080"
      #- "5683:5683"
    volumes:
      - "./OM2M/configuration/config.ini:/home/in-cse/configuration/config.ini"
    depends_on:
      - mqtt-broker
    links:
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto:latest
    command: /bin/sh -c "touch /mosquitto/config/pwfile && /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./MQTT/config:/mosquitto/config"
      - "./MQTT/data:/mosquitto/data"
      - "./MQTT/log:/mosquitto/log"
